name: sumo
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_joystick: ^0.0.4
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.3.0
  fluttertoast: ^8.2.4
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  async: ^2.11.0
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
